# Generated by Django 5.0.7 on 2024-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('competitors', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('sides', models.JSONField(default=list)),
                ('site_one_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('site_two_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('site_one_name', models.CharField(max_length=50)),
                ('site_one_link', models.URLField(max_length=255)),
                ('site_two_name', models.CharField(max_length=50)),
                ('site_two_link', models.URLField(max_length=255)),
            ],
        ),
    ]
