# Generated by Django 5.0.7 on 2024-07-15 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrageopportunity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arbitrageopportunity',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitrageopportunity',
            name='found',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
