databases:
  - name: arbitrage
    plan: free
    databaseName: arbitrage
    user: arbitrage_k15d_user

services:
  - type: web
    plan: free
    name: latvian-arbitrage
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn server.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arbitrage
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
