from datetime import datetime
import requests

def casino777_tennis():
    site_name = "casino777"
    site_link = "https://casino777.lv"
    urls = [
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLivenow?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportId=68&showAllEvents=true',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetUpcoming?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportId=68&showAllEvents=false&count=50&hasStreaming=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=0&categoryids=542&champids=0&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=0&categoryids=542&champids=0&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=3158&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17447&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17450&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31918&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31917&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31766&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&culture=en-GB&numFormat=en&integration=casino777&langId=8&skinName=casino777&configId=1&countryCode=LV&deviceType=Desktop&champids=32074&group=ChampsWithoutDates&withLive=false&filterSingleNodes=2&sportids=68&period=periodall&outrightsDisplay=Outrights',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31929&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31895&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&culture=en-GB&numFormat=en&integration=casino777&langId=8&skinName=casino777&configId=1&countryCode=LV&deviceType=Desktop&champids=3038&group=ChampsWithoutDates&withLive=false&filterSingleNodes=2&sportids=68&period=periodall&outrightsDisplay=Outrights',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=16911&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32012&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32007&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31928&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31927&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31804&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=36895&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=36894&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=42379&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32024&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32021&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32024&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=36858&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=37675&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=5171&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17362&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17063&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=47706&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=33655&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=44111&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31715&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=32559&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=42379&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=42379&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31422&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=31422&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17466&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=17466&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=0&categoryids=0&champids=43338%2C33224%2C43323%2C33770%2C33087%2C33779%2C36419%2C31800&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=0&categoryids=0&champids=43338%2C33224%2C43323%2C33770%2C33087%2C33779%2C36419%2C31800&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=43338&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=43338&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=44279&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=44279&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetLiveEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=18338&group=AllEvents&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0&hasLiveStream=false',
        'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents?timezoneOffset=-180&langId=8&skinName=casino777&configId=1&culture=en-GB&countryCode=LV&deviceType=Desktop&numformat=en&integration=casino777&sportids=68&categoryids=0&champids=18338&group=AllEvents&period=periodall&withLive=false&outrightsDisplay=none&marketTypeIds=&couponType=0&marketGroupId=0'
    ]
    events = []

    try:
        for url in urls:
            response = requests.get(url)
            data = response.json()

            for item in data['Result']['Items']:
                for event in item['Events']:
                    if not event["IsVirtual"]:
                        event_name = event["CategoryName"]
                        competitors = event["Name"]
                        date = datetime.strptime(event["EventDate"], "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%d %H:%M:%S")
                        # is_live = event["IsLiveEvent"]
                        # live_current_time = event["LiveCurrentTime"] if is_live else None
                        market = "winner"
                        odds = []
                        for market in event['Items']:
                            if market['Name'] == 'Winner':
                                for selection in market['Items']:
                                    odds.append(selection["Price"])
                        if len(odds) > 1:
                            events.append({
                                'category': event_name,
                                'competitors': competitors,
                                'date': date,
                                # 'is_live': is_live,
                                # 'live_current_time': live_current_time,
                                'odds': odds,
                                'site_name': site_name,
                                'site_link': site_link
                            })
    except Exception:
        return events

    return events

# print(casino777_tennis())